### ISSUE TITLE
What's resource of hardware ?

### ISSUE THREAD

**Issue by Delarren** [Vadorequest/AAD1#5]
Hi Vadorequest ! I am interesting in your project. Congrulations! I looked almost all documents but i couldn't see resource of hardware except arduino yun. Can you share all of items and their identificaitons/trademarks. Sorry for my English :) Thank you !

**Comment by Vadorequest** [comment]
Hello!

Did you take a look at this document? https://github.com/Vadorequest/AAD1/blob/master/Design/Documentation/3%20-%20WCC%20-%20Design.pdf
