### ISSUE TITLE
can't do second command

### ISSUE THREAD

**Issue by alexman23** [Vadorequest/AAD1#6]
hi Vadorequest i try to do the same project as yours using your code but without motorshield. the yun is reading the first command(e.g forward) but never listen to a second command. what you
think its wrong edition of android studio, code?

**Comment by chingte** [comment]
hi Vadorequest , thanks your code, and met the same problem.

**Comment by Vadorequest** [comment]
Sadly, I can't help much about that. I haven't played around with Yun since 2014. There could be various reasons. I don't have any clue, sorry.
